### ISSUE TITLE
Is there a way to enable hot reload?

### ISSUE THREAD

**Issue by brummm** [tralves/nativescript-vue-webpack-template#10]
The .vue file is a nice addition, but developing without hot reload is tedious...

**Comment by tralves** [comment]
Agreed. 

The [rollup template](https://github.com/tralves/nativescript-vue-rollup-template) allows liveSync. It is not as good as hot reload, but it is much better than bundling everything every time.

NativeScript does not have hot reload yet. When it gets added to NS, we will bring it to ns-vue.

**Comment by tralves** [comment]
I just updated this package. It now supports live sync.
