### ISSUE TITLE
Real Device Bug

### ISSUE THREAD

**Issue by ukik** [tralves/nativescript-vue-webpack-template#11]
I have successfully using this template to make APK, so impressive size is 13MB and startup just 3-4 seconds

But when Apps I minimize using Back button or else, then I open again both from Icon or from Home, then show me 

"View already has a parent. View: Page (4) Parent: Frame (10), undefined"

**Comment by tralves** [comment]
Hi!

This is actually a known `nativescript-vue` bug. You may check its progress here: https://github.com/rigor789/nativescript-vue/issues/59
