### ISSUE TITLE
v-model doesn't work in Vue component

### ISSUE THREAD

**Issue by mattsims** [tralves/nativescript-vue-webpack-template#13]
First off, thanks for you great work with NativeScript-Vue!

Not sure if this is a problem with this template, or something deeper, but thought I should raise it.

Steps to reproduce:

1. Install and run as per the README instructions.
2. Add a data object to the main `Vue(){}` declaration in `app.js`, i.e. 
```
  data: {
      val: 'Vue.js'
  },
```
3. Add a text field to the template object that is bound to this new data value, i.e.
```
<text-field v-model="val"></text-field>
```
4. Run the app and confirm that data binding works as expected, i.e. the new text field contains the text 'Vue.js'.
5. Now add the same text field within the `VueComponent.vue` component file, i.e.
```
<template>
  <stack-layout>
    <label>A {{val}} component.</label>
    <text-field v-model="val"></text-field>
  </stack-layout>
</template>
```
6. Run the app and notice that the v-model binding in the component does not work.

It would be great to know if this is reproducible, or whether it's just something to do with my specific install. I'm going to try the same thing with [your rollup template](https://github.com/tralves/nativescript-vue-rollup-template) and see if that works as expected.

**Comment by mattsims** [comment]
Rollup version works fine with v-model binding in component right out of the box, so guessing it must be webpack-related.

**Comment by tralves** [comment]
Sorry for the late reply. 

Yes, it is reproducible and I am trying to fix it for some time now. Still have no clues. If you find anything, let me know.

`v-binds` don't seem to be working neither...

**Comment by tralves** [comment]
I think I finally fixed this!
I had to create a `vue-loader` to get around this issue.
Can you please try again?

**Comment by 34r7h** [comment]
Hey is there another step to get v-model working?

**Comment by tralves** [comment]
I don't think so. It should be working now...
