### ISSUE TITLE
tns folder refactoring

### ISSUE THREAD

**Issue by paolodina** [tralves/nativescript-vue-webpack-template#19]
Transform the `tns` folder into a "hidden" `.tns` folder and everything in there is managed automatically.

The user should never `cd .tns`, but instead would run npm/webpack scripts to do everything. Assets, bundles, etc are copied and managed automatically. the `.tns` folder is disposable and reconstructed automatically.

Ref. https://nativescriptcommunity.slack.com/archives/C4ZS6K6E6/p1512133453000075

**Comment by tralves** [comment]
This project is now deprecated.
