### ISSUE TITLE
tns does not see css changes

### ISSUE THREAD

**Issue by alekspetrov** [tralves/nativescript-vue-webpack-template#25]
I changed the styles in a single-file component, webpack worked, but tns does not see changes.

Am I the only who has this behaviour?

**Comment by nusendra** [comment]
same issue

**Comment by vaneyck** [comment]
I am also facing the same issue. I have some styling defined in a component but this is not applied in the app.

**Comment by warhsn** [comment]
Same issue here, im editing the app.scss file.

**Comment by nusendra** [comment]
Don't use this template anymore
u guys have to migrate to this repo https://github.com/nativescript-vue/vue-cli-template

**Comment by tralves** [comment]
This template is being deprecated in favor of the [Vue Cli template](https://github.com/nativescript-vue/vue-cli-template). `vue-cli` simply deals with these problems much nicely...
