### ISSUE TITLE
JS: Error: Css styling failed: Error: undefined:1:16: missing '{'

### ISSUE THREAD

**Issue by Zomis** [tralves/nativescript-vue-webpack-template#26]
I used your template but while running it I got the same output over and over again, and the livereload got stuck in a loop.

As I posted on Slack, https://nativescriptcommunity.slack.com/archives/C4ZS6K6E6/p1516551973000033 :

When running nativescript-vue-webpack-template with `tns debug android` as described in https://github.com/tralves/nativescript-vue-webpack-template I'm encountering some strange behavior that the command continuously deploy and install the app, run it, then shuts down the app on my phone and deploys again and starts the process again, over and over again.

This output sequence is repeated all the time:

```Successfully transferred all files.
Using  c:\Users\Simon\Desktop\vue-native\sample-app\tns\platforms\android\app\build\outputs\apk\sampleapp-debug.apk
device: 6042c2b7 debug port: 40000

# NativeScript Debugger started #
To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40000

Executing before-prepare hook from c:\Users\Simon\Desktop\vue-native\sample-app\tns\hooks\before-prepare\nativescript-dev-android-snapshot.js
Preparing project...
Project successfully prepared (Android)
Executing after-prepare hook from c:\Users\Simon\Desktop\vue-native\sample-app\tns\hooks\after-prepare\nativescript-dev-android-snapshot.js
ActivityManager: Start proc org.nativescript.sampleapp for activity org.nativescript.sampleapp/com.tns.NativeScriptActivity: pid=27977 uid=10263 gids={50263, 9997, 1028, 1015, 3003} abi=armeabi-v7a
JS: Error: Css styling failed: Error: undefined:1:16: missing '{'
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> TagName(TextNode(comment))
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> ParentNode(TextNode(comment))
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> NextSibling(TextNode(comment))
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> CreateElement(page)
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> CreateElement(stack-layout)
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> CreateElement(label)
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> CreateTextNode(A JS component.)
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> AppendChild(ElementNode(label), TextNode$1(null))
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> AppendChild(ElementNode(stacklayout), ElementNode(label))
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> CreateElement(label)
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> SetAttribute(ElementNode(label), data-v-0f0e8576, )
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> CreateTextNode(A Vue.js component.)
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> AppendChild(ElementNode(label), TextNode$1(null))
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> AppendChild(ElementNode(stacklayout), ElementNode(label))
JS: {NSVue (Vue: 2.5.2 | NSVue: 0.1.25)} -> AppendChild(ElementNode(page), ElementNode(stacklayout))```

**Comment by denisraison** [comment]
Hey @Zomis, did you get an answer for it? I'm getting the same issue.

**Comment by jlooper** [comment]
This happens to me on iOS when I have an error in my code. I think Livesync and Webpack get out of sync and a loop starts. 

To stop it, I stop all the processes, then restart Webpack, then start tns after Webpack builds.

**Comment by jlooper** [comment]
Also I've gotten into trouble when running `tns` outside of the tns folder. Make sure you have your terminals running in the right folder. This bit me the other day.

**Comment by Zomis** [comment]
@denisrai Haven't had time to try it again since last time unfortunately. Occupied with other projects at the moment.

**Comment by ReeVicente** [comment]
Same issue here, i have restart and work, but when i begin code and live reload the problem come back

**Comment by nusendra** [comment]
same issue here

**Comment by denisraison** [comment]
Has someone tried using this template instead?
https://github.com/nativescript-vue/nativescript-vue-webpack-template

I haven't had time to test it out again...

**Comment by nusendra** [comment]
not yet @denisrai 

do you have experience about that template ?

**Comment by ReeVicente** [comment]
@denisrai  i have tried and have some bugs

**Comment by rigor789** [comment]
Yes that template (as noted in the repo) is still a WIP. I wish I could have more time that I do currently to go over and make it work 100%.

**Comment by milanBug** [comment]
@denisrai I keep getting this error every time I try to start that template with `npm run tns -- run android`
`Error: com.tns.NativeScriptException: Failed to find module: "./layout-base-common", relative to: app/` :disappointed:

**Comment by denisraison** [comment]
@milanBug yep, I was getting the same thing...
It seems to be some webpack config issue, not sure. I didn't have much time to investigate.

**Comment by phbdemorais** [comment]
This template its fine
https://github.com/nativescript-vue/vue-cli-template

**Comment by nusendra** [comment]
whoa. this must be the problem solver

thanks @PedroBatista333

**Comment by denisraison** [comment]
YAAAY! 
That works @PedroBatista333  thanks for the heads up.

OBS: Just make sure you don't  name your project "nativescript-vue" (as I did...) when you do that. You mess up with the externals in the webpack.config file. I mean, you can use but you'll need to change your webpack.config...

Cheers,

**Comment by nusendra** [comment]
just waiting for the docs update about this template. the docs still outdated

**Comment by kryvonos-v** [comment]
I figured out this problem occurs if you have blank CSS file.

**Comment by tralves** [comment]
This template is being deprecated in favor of the [Vue Cli template](https://github.com/nativescript-vue/vue-cli-template). `vue-cli` simply deals with these problems much nicely...

**Comment by delanick** [comment]
I have thhis issue currently on iOS on {N} Core, JS. Anyone know what can be done? It often loads the app on iPhone but without and CSS applied.

Please help - seriously frustrating!
