### ISSUE TITLE
Which Instructions Should Be Followed?

### ISSUE THREAD

**Issue by aaronksaunders** [tralves/nativescript-vue-webpack-template#27]
There are a set of instructions on how to use the template scripts listed in the README and then another set when you install... neither seem to work on my mac?

Not sure what I am missing... also when I install the template there are incorrect files in the `tns` directory... after removing and rebuilding I get the following error

```
ld: warning: directory not found for option '-F/Users/aaronsaunders/dev/projects/nativescript/hello-ns-vue/platforms/ios/../../node_modules/tns-core-modules-widgets/platforms/ios'
ld: framework not found TNSWidgets
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: warning: directory not found for option '-F/Users/aaronsaunders/dev/projects/nativescript/hello-ns-vue/platforms/ios/../../node_modules/tns-core-modules-widgets/platforms/ios'
ld: framework not found TNSWidgets
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tralves** [comment]
Hi!

I just followed the instructions on the README to start a new project and it worked.
What is this other set of instructions you mentioned? Where is it?

**Comment by aaronksaunders** [comment]
it works but the application that runs is using the files already in the `tns/app` folder... not the `VueComponent.vue` file and the `JsComponent.js` file

this set of instructions...

```
NativeScript Webpack plugin was successfully added.
You can now bundle your project with the following npm scripts:
    - "npm run build-android-bundle" to build for android.
    - "npm run build-ios-bundle" to build for ios.
    - "npm run start-android-bundle" to run on android.
    - "npm run start-ios-bundle" to run on ios.
You can also pass the "--uglify" flag to use UglifyJS for minification.
For more information check out https://docs.nativescript.org/tooling/bundling-with-webpack#bundling.
```

**Comment by rigor789** [comment]
Ah, that is indeed a little confusing, the instructions from this repo should be used, the ones you pasted are coming from the nativescript-dev-webpack plugin which is not used directly for this template (it's used in the webpack.config.js file).

**Comment by aaronksaunders** [comment]
even when using those instructions I am getting inconsistent results.. i have it working on one machine, committed code to github - https://github.com/aaronksaunders/ns-vue-wp-app

and when i do a clean and clone I am getting this error
```
file:///app/components/Home.vue:1: JS ERROR SyntaxError: Unexpected token '<'
```

**Comment by rigor789** [comment]
That error seems like you are trying to run `tns` inside the root folder instead of the tns folder.

**Comment by aaronksaunders** [comment]
so I have figured out what the issues are for me, it is the symlinking that is being used when the project is first created... so when i commit the code to a repo and then check it out in another environment it just doesn't work? is there a way to completely reset the tns directlty and the symlinks back to the main app folder?

thanks again for your help, i think this can be a promising solution for integrating vuejs with nativescript

**Comment by rigor789** [comment]
Symlinks are a little tricky to get right on all platforms, we are working on a new template which will not rely on symlinks, where the "tns" folder (will be dist/native) will be completely disposable, and out of source control, which should make it work better across different environments / platforms

**Comment by aaronksaunders** [comment]
So it seems like there is not real production solution for single component files, .vue, using nativescript and vue?

**Comment by rigor789** [comment]
That's correct, since nativescript-vue itself isn't officially production ready yet. Working on it though! :)
