### ISSUE TITLE
TypeError: dep.getResourceIdentifier is not a function

### ISSUE THREAD

**Issue by Lavhe** [tralves/nativescript-vue-webpack-template#29]
When i run 

> webpack --watch --env.tns --env.android

I get this ...

![vueissue](https://user-images.githubusercontent.com/13318139/36741341-8120e74c-1bed-11e8-9257-cb36e719460c.png)

**Comment by rigor789** [comment]
The template has not been updated for webpack 4, you should try with webpack 3. (you can install it locally and use `npx webpack --version` to run the local webpack)

**Comment by Lavhe** [comment]
Wow thanks it is working.
