### ISSUE TITLE
Is there a way to configure es-stage ?

### ISSUE THREAD

**Issue by asafyish** [tralves/nativescript-vue-webpack-template#4]
We can see that 'import' is working, but something more advanced, like
```js
const a = {
...a,
b:1
};
```
is not working. Is there a quick guide on how to configure it or we need to dig in webpack/babel configuration ?

**Comment by tralves** [comment]
I will be adding es6 stage-2 support soon. 

Should be easy to add babel support. I have done that in the [rollup template](https://github.com/tralves/nativescript-vue-rollup-template).
