### ISSUE TITLE
webpack can't resolve res://name

### ISSUE THREAD

**Issue by saknarak** [tralves/nativescript-vue-webpack-template#9]
when use res:// in style, webpack can't bundle

ERROR in ../~/css-loader!../~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-a648ff1a","scoped":true,"hasInlineConfig":false}!../~/sass-loader/lib/loader.js!../~/vue-loader/lib/selec
tor.js?type=styles&index=0!./VueComponent.vue
    Module not found: Error: Can't resolve './res://icon' in  ...

Bay be it should add ignore this scheme in webpack.config.js?

**Comment by tralves** [comment]
Please show me how you are using `res://` in your code.

Thx

**Comment by KABBOUCHI** [comment]
please try the following
``` 
        {
            test: /\.vue$/,
            loader: 'vue-loader',
            options: {
                url : false,
                loaders : {
                    css : extractCSS.extract("css-loader"),
                    scss : extractCSS.extract({
                        use: ['css-loader', 'sass-loader'],
                        fallback: 'vue-style-loader'
                    })
                }
            }
        },
```

or

``` 
        {
            test: /\.vue$/,
            loader: 'vue-loader',
            options: {
                loaders : {
                    css : extractCSS.extract("css-loader"),
                    scss : extractCSS.extract({
                        use: ['css-loader?-url', 'sass-loader'],
                        fallback: 'vue-style-loader'
                    })
                }
            }
        },
```

**Comment by saknarak** [comment]
thank you very much. its working now.

**Comment by tralves** [comment]
Hi!

How did you solve this issue? I tried @KABBOUCHI solution with no luck. I am trying to add a `res://` asset in a .vue file, but webpack keeps trying to resolve it...
